package cn.ssm.model;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name ="ssm_admin")
public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_admin.id
     *
     * @mbggenerated
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_admin.admin_user
     *
     * @mbggenerated
     */
    private String adminUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_admin.admin_password
     *
     * @mbggenerated
     */
    private String adminPassword;
    private  String title;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_admin.textarea
     *
     * @mbggenerated
     */
    private String textarea;




    public Admin() {
    }

    public Admin(Long id, String adminUser, String adminPassword, String title, String textarea) {
        this.id = id;
        this.adminUser = adminUser;
        this.adminPassword = adminPassword;
        this.title = title;
        this.textarea = textarea;
    }

    public Admin(String textarea) {
        this.textarea = textarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_admin.id
     *
     * @return the value of ssm_admin.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_admin.id
     *
     * @param id the value for ssm_admin.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_admin.admin_user
     *
     * @return the value of ssm_admin.admin_user
     *
     * @mbggenerated
     */
    public String getAdminUser() {
        return adminUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_admin.admin_user
     *
     * @param adminUser the value for ssm_admin.admin_user
     *
     * @mbggenerated
     */
    public void setAdminUser(String adminUser) {
        this.adminUser = adminUser == null ? null : adminUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_admin.admin_password
     *
     * @return the value of ssm_admin.admin_password
     *
     * @mbggenerated
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_admin.admin_password
     *
     * @param adminPassword the value for ssm_admin.admin_password
     *
     * @mbggenerated
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_admin.textarea
     *
     * @return the value of ssm_admin.textarea
     *
     * @mbggenerated
     */
    public String getTextarea() {
        return textarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_admin.textarea
     *
     * @param textarea the value for ssm_admin.textarea
     *
     * @mbggenerated
     */
    public void setTextarea(String textarea) {
        this.textarea = textarea == null ? null : textarea.trim();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "id=" + id +
                ", adminUser='" + adminUser + '\'' +
                ", adminPassword='" + adminPassword + '\'' +
                ", title='" + title + '\'' +
                ", textarea='" + textarea + '\'' +
                '}';
    }
}