package cn.ssm.model;


import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "ssm_board")
public class Board {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_board.id
     *
     * @mbggenerated
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_board.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_board.board
     *
     * @mbggenerated
     */
    private String textarea;

    public Board() {
    }



    public Board(Long id, String title, String textarea) {
        this.id = id;
        this.title = title;
        this.textarea = textarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_board.id
     *
     * @return the value of ssm_board.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_board.id
     *
     * @param id the value for ssm_board.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_board.title
     *
     * @return the value of ssm_board.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_board.title
     *
     * @param title the value for ssm_board.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_board.board
     *
     * @return the value of ssm_board.board
     *
     * @mbggenerated
     */
    public String getTextarea() {
        return textarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_board.board
     *
     * @param board the value for ssm_board.board
     *
     * @mbggenerated
     */
    public void setTextarea(String textarea) {
        this.textarea = textarea == null ? null : textarea.trim();
    }

    @Override
    public String toString() {
        return "Board{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", textarea='" + textarea + '\'' +
                '}';
    }
}