package cn.ssm.model;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "ssm_recruitment")
public class Recruitment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_recruitment.id
     *
     * @mbggenerated
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_recruitment.rec_id
     *
     * @mbggenerated
     */
    private String recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_recruitment.res_id
     *
     * @mbggenerated
     */
    private String resId;

    private Resume resumes;

    private Recruit recruits;

    public Recruitment(String id, String recId, String resId, Resume resumes, Recruit recruits) {
        this.id = id;
        this.recId = recId;
        this.resId = resId;
        this.resumes = resumes;
        this.recruits = recruits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_recruitment.id
     *
     * @return the value of ssm_recruitment.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_recruitment.id
     *
     * @param id the value for ssm_recruitment.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_recruitment.rec_id
     *
     * @return the value of ssm_recruitment.rec_id
     *
     * @mbggenerated
     */
    public String getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_recruitment.rec_id
     *
     * @param recId the value for ssm_recruitment.rec_id
     *
     * @mbggenerated
     */
    public void setRecId(String recId) {
        this.recId = recId == null ? null : recId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_recruitment.res_id
     *
     * @return the value of ssm_recruitment.res_id
     *
     * @mbggenerated
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_recruitment.res_id
     *
     * @param resId the value for ssm_recruitment.res_id
     *
     * @mbggenerated
     */
    public void setResId(String resId) {
        this.resId = resId == null ? null : resId.trim();
    }

    public Resume getResumes() {
        return resumes;
    }

    public void setResumes(Resume resumes) {
        this.resumes = resumes;
    }

    public Recruit getRecruits() {
        return recruits;
    }

    public void setRecruits(Recruit recruits) {
        this.recruits = recruits;
    }

    @Override
    public String toString() {
        return "Recruitment{" +
                "id='" + id + '\'' +
                ", recId='" + recId + '\'' +
                ", resId='" + resId + '\'' +
                ", resumes=" + resumes +
                ", recruits=" + recruits +
                '}';
    }
}