package cn.ssm.model;

public class Resume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.job_category
     *
     * @mbggenerated
     */
    private String jobCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.work_place
     *
     * @mbggenerated
     */
    private String workPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.salary_expectation
     *
     * @mbggenerated
     */
    private String salaryExpectation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.working_life
     *
     * @mbggenerated
     */
    private String workingLife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.highest_degree
     *
     * @mbggenerated
     */
    private String highestDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_resume.u_id
     *
     * @mbggenerated
     */
    private String uId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.id
     *
     * @return the value of ssm_resume.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.id
     *
     * @param id the value for ssm_resume.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.job_category
     *
     * @return the value of ssm_resume.job_category
     *
     * @mbggenerated
     */
    public String getJobCategory() {
        return jobCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.job_category
     *
     * @param jobCategory the value for ssm_resume.job_category
     *
     * @mbggenerated
     */
    public void setJobCategory(String jobCategory) {
        this.jobCategory = jobCategory == null ? null : jobCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.work_place
     *
     * @return the value of ssm_resume.work_place
     *
     * @mbggenerated
     */
    public String getWorkPlace() {
        return workPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.work_place
     *
     * @param workPlace the value for ssm_resume.work_place
     *
     * @mbggenerated
     */
    public void setWorkPlace(String workPlace) {
        this.workPlace = workPlace == null ? null : workPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.salary_expectation
     *
     * @return the value of ssm_resume.salary_expectation
     *
     * @mbggenerated
     */
    public String getSalaryExpectation() {
        return salaryExpectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.salary_expectation
     *
     * @param salaryExpectation the value for ssm_resume.salary_expectation
     *
     * @mbggenerated
     */
    public void setSalaryExpectation(String salaryExpectation) {
        this.salaryExpectation = salaryExpectation == null ? null : salaryExpectation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.name
     *
     * @return the value of ssm_resume.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.name
     *
     * @param name the value for ssm_resume.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.gender
     *
     * @return the value of ssm_resume.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.gender
     *
     * @param gender the value for ssm_resume.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.working_life
     *
     * @return the value of ssm_resume.working_life
     *
     * @mbggenerated
     */
    public String getWorkingLife() {
        return workingLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.working_life
     *
     * @param workingLife the value for ssm_resume.working_life
     *
     * @mbggenerated
     */
    public void setWorkingLife(String workingLife) {
        this.workingLife = workingLife == null ? null : workingLife.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.highest_degree
     *
     * @return the value of ssm_resume.highest_degree
     *
     * @mbggenerated
     */
    public String getHighestDegree() {
        return highestDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.highest_degree
     *
     * @param highestDegree the value for ssm_resume.highest_degree
     *
     * @mbggenerated
     */
    public void setHighestDegree(String highestDegree) {
        this.highestDegree = highestDegree == null ? null : highestDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.phone_number
     *
     * @return the value of ssm_resume.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.phone_number
     *
     * @param phoneNumber the value for ssm_resume.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_resume.u_id
     *
     * @return the value of ssm_resume.u_id
     *
     * @mbggenerated
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_resume.u_id
     *
     * @param uId the value for ssm_resume.u_id
     *
     * @mbggenerated
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }
}