package cn.ssm.dao;

import cn.ssm.model.Admin;
import cn.ssm.model.AdminExample;
import java.util.List;

import cn.ssm.util.BaseMapper;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper extends BaseMapper<Admin>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    Admin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Admin record);


    Admin loginAdmin(Admin admin);

}