package cn.ssm.dao;

import cn.ssm.model.Board;
import cn.ssm.model.BoardExample;
import java.util.List;

import cn.ssm.util.BaseMapper;
import org.apache.ibatis.annotations.Param;

public interface BoardMapper extends BaseMapper<Board>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int countByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int deleteByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int insertSelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    List<Board> selectByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    Board selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Board record, @Param("example") BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Board record, @Param("example") BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_board
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Board record);

    int updateEditor(Board board);

    Board showBoard( Long id);

    public List<Board> selectTitleByPage(@Param(value="startPos") Integer startPos,@Param(value="pageSize") Integer pageSize);

    /**
     *
     * @param
     * @return
     */
    public int getTitleCount();
}