package cn.ssm.dao;

import cn.ssm.model.Recruitment;
import cn.ssm.model.RecruitmentExample;
import java.util.List;

import cn.ssm.util.BaseMapper;
import org.apache.ibatis.annotations.Param;

public interface RecruitmentMapper extends BaseMapper<Recruitment> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruitment
     *
     * @mbggenerated
     */
    int countByExample(RecruitmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruitment
     *
     * @mbggenerated
     */
    int deleteByExample(RecruitmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruitment
     *
     * @mbggenerated
     */
    int insert(Recruitment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruitment
     *
     * @mbggenerated
     */
    int insertSelective(Recruitment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruitment
     *
     * @mbggenerated
     */
    List<Recruitment> selectByExample(RecruitmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruitment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Recruitment record, @Param("example") RecruitmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruitment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Recruitment record, @Param("example") RecruitmentExample example);
}