package cn.ssm.dao;

import cn.ssm.model.Recruit;
import cn.ssm.model.RecruitExample;
import java.util.List;

import cn.ssm.util.BaseMapper;
import org.apache.ibatis.annotations.Param;

public interface RecruitMapper extends BaseMapper<Recruit> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int countByExample(RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int deleteByExample(RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int insert(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int insertSelective(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    List<Recruit> selectByExample(RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    Recruit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Recruit record, @Param("example") RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Recruit record, @Param("example") RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recruit record);
}