package cn.ssm.dao;

import cn.ssm.model.Resumement;
import cn.ssm.model.ResumementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResumementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_resumement
     *
     * @mbggenerated
     */
    int countByExample(ResumementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_resumement
     *
     * @mbggenerated
     */
    int deleteByExample(ResumementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_resumement
     *
     * @mbggenerated
     */
    int insert(Resumement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_resumement
     *
     * @mbggenerated
     */
    int insertSelective(Resumement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_resumement
     *
     * @mbggenerated
     */
    List<Resumement> selectByExample(ResumementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_resumement
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Resumement record, @Param("example") ResumementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_resumement
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Resumement record, @Param("example") ResumementExample example);
}